use_frameworks!

target 'TreasureDataExample' do
  platform :ios, '12.0'
  pod 'TreasureData-iOS-SDK', :path => '..'
end

target 'TreasureDataTVOSExample' do
  platform :tvos, '12.0'
  pod 'TreasureData-iOS-SDK', :path => '..'
end
