#!/usr/bin/env bash

set -e

if [ -d "$HOME/.cocoapods/repos/master" ]; then
    echo Local CocoaPods repo has been restored from cache
    # Not sure if caching for Pods that fetched from CircleCI's S3 is a wise choice,
    # seems like a doubly layered caching.
else
    curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
fi

pod install

exit 0
