#!/usr/bin/env bash

set -o pipefail

DESTINATION="$1"
LOG_FILE="$2"
TEST_RESULTS_FILE="$3"

cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")"

xcodebuild \
    -workspace TreasureData.xcworkspace \
    -scheme TreasureData \
    -sdk iphonesimulator \
    -disable-concurrent-destination-testing \
    -destination "$DESTINATION" \
    TD_DEV_MASTER_KEY="$TD_DEV_MASTER_KEY" \
    test \
    | gsed -u '1,100s/^\(.*TD_DEV_MASTER_KEY\s*=\s*\)\(\b.*\b\)\(.*\)$/\1XXXXXXXXXXX\3/g' \
    | tee "$LOG_FILE" \
    | xcpretty --report junit

test_status=$?

mv ./build/reports/junit.xml "$3"

if [ $test_status -ne 0 ]; then
    exit $test_status
fi

exit 0
