#!/usr/bin/env bash

set -eo pipefail

destination="$1"
log_file="$2"

xcodebuild \
    -workspace TreasureData.xcworkspace \
    -scheme TreasureData \
    -sdk iphonesimulator \
    -disable-concurrent-destination-testing \
    -destination "$destination" \
    TD_DEV_MASTER_KEY=${TD_DEV_MASTER_KEY} \
    test \
    | sed 's/^\(.*TD_DEV_MASTER_KEY[[:space:]]*=[[:space:]]*\)\([[:<:]].*[[:>:]]\)\(.*\)$/\1XXXXXXXXXXX\3/' \
    | tee "$log_file" \
    | xcpretty
